# Generated by Django 6.0 on 2026-06-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spider_img',
            name='title',
        ),
    ]
