# Generated by Django 6.0 on 2026-06-22 00:24

import spider_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_app', '0002_remove_spider_img_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spider_img',
            name='spider',
        ),
        migrations.AlterField(
            model_name='spider_img',
            name='img',
            field=models.ImageField(upload_to=spider_app.models.perform_upload_img),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
