# Generated by Django 6.0 on 2026-06-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_app', '0003_remove_spider_img_spider_alter_spider_img_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=50),
        ),
    ]
